# Generated by Django 5.2.6 on 2025-09-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar/default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
